on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Should fail exit code 42
    steps:
      - uses: actions/checkout@v2
        with:
          # Contains [ci skip] in message body
          ref: '89e4cb4c830463466868cfebb8ad6c826285c40f'
          fetch-depth: '0'
      - uses: mstachniuk/ci-skip@master
        with:
          fail-fast: true
      - name: Verification
        run: |
          echo "The previous step should exiting with 42 code and this code should not run"